version: 2.1

orbs:
  yarn: artsy/yarn@6.1.0
  auto: artsy/auto@2.0.0

deploy: &deploy
  context: npm-deploy

not_main: &not_main
  filters:
    branches:
      ignore: main

only_main: &only_main
  filters:
    branches:
      only: main

workflows:
  build_and_verify:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - yarn/test:
          args: -c
          requires:
            - yarn/workflow-queue
      # Pr builds
      - auto/publish-canary:
          <<: *not_main
          <<: *deploy
          requires:
            - yarn/test
            - yarn/update-cache
      # Releases
      - auto/publish:
          <<: *only_main
          <<: *deploy
          requires:
            - yarn/test
            - yarn/update-cache
